name: nvm
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: nvm install
        shell: bash --login {0}
      - run: node --version
        shell: bash --login {0}
